### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by jinguoli** [podgib/atom-protobuf#3]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:565:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:187:43)
```

**Comment by jinguoli** [comment]
atom version: 0.189.0 4/2/2015, 5:44:55 AM

**Comment by podgib** [comment]
Weird, deprecation cop doesn't complain about this on my machine. I've pushed an update that I hope fixes this, but I don't know, as the problem never showed up for me any way. Let me know whether it's fixed.

**Comment by jinguoli** [comment]
it's fixed now, thanks.
