### ISSUE TITLE
syntax highlight no work

### ISSUE THREAD

**Issue by jinguoli** [podgib/atom-protobuf#4]
this is ok:
```protobuf
message StringPair {
    required bytes key = 1;
    optional bytes val = 2;
}
```
after is no highlight:
```protobuf
message StringPair
{
    required bytes key = 1;
    optional bytes val = 2;
}
```

**Comment by basilfx** [comment]
+1.

Having the same issue. Google's style guide does not forbid this style, and the compiler parses this without any issues.

**Comment by OliverRC** [comment]
Same here, does not work with braces on new lines.
