### ISSUE TITLE
Proto v3 not highlighted

### ISSUE THREAD

**Issue by swsnider** [podgib/atom-protobuf#6]
For instance, the following code is valid (and compiles) but does not highlight with your module:

```protobuf
message ReadChunkResponse {
  string id = 1;
  uint64 start_byte = 2;
  uint64 end_byte = 3;
  bytes content = 4;
}
```

**Comment by podgib** [comment]
Thanks. I only use protobuf v2, so let me know if there's any other compatibility issues
