### ISSUE TITLE
Support User-defined file types

### ISSUE THREAD

**Issue by NullParameter** [podgib/atom-protobuf#7]
For one reason or another, my workplace has taken to naming our proto files with different file extensions than just 'proto', like 'messages'.

Sadly, every time I update the plugin now I find myself going into the grammars file to add these additional file types, because my additions always get overwritten.  It would be much better if these different files types were something that could be configured instead.  I'm not sure if that is possible, or if Atom requires you to specify them ahead of time in your grammar file(s), but I would love this addition, because this plugin has been a great addition.

Thank you, and keep up the good work!

**Comment by podgib** [comment]
Seems that this is a more general problem that will hopefully get a fix soon: https://github.com/atom/atom/issues/1718
For now, this package allows you to specify extra extensions in your config.cson, so they won't be overwritten when you upgrade the package: https://atom.io/packages/file-types

**Comment by podgib** [comment]
Custom file types are [supported](https://github.com/atom/atom/pull/8144) in core via the `core.customFileTypes` setting as of 1.0.8, so no need to write this into the package.
